### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by nerdburt** [jeffreymcclain/Computer-Architecture-Project#1]
Hello, am quite interested in your simulation of an entire architecture in LogicWorks.  Managed to get this running nicely in Windows 10 with LogicWorks 5.0   Very nicely done!

Feature I am wondering about is whether there would be a text file, or ROM chip, or batch file that could load a test program, so that a simulated program could be seen running.   i.e.:  just loading a register with a number or adding two numbers.   The simplest thing would be if a readme.txt file could be provided would probably do do the trick, just showing some sample assembly instructions/code that could be loaded to the simulation.

**Comment by jeffreymcclain** [comment]
I'm gonna be honest with you, I made this program years ago for a school
project and don't really remember the details of how it works.

Feel free to fork / modify the repository however you'd like, I'm frankly
surprised you even managed to find it.

- Jeffrey McClain

**Comment by nerdburt** [comment]
Good evening, Jeffrey.

Thanks for your quick response to this, much appreciated.    I was looking for a working Logicworks CPU system, and yours was the most complete.   It took a bit of sleuthing, found some stuff in Canada, MIT, and a few other universities.

Will consider this closed, and have already been figuring a few things out with the RAM chip.

Great work on this!   If you ever happen to stumble on any notes or docs you made for this, please feel free to email them to me, and I may add them to this project as a fork etc.   This is purely for educational purposes for me and my family, as we are interested in how this all works.    It is a much more updated and sophisticated system that we had setup when I was in computer science many years ago.

Thanks again,

Rick

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jeffreymcclain** [comment]
I'm glad you found my project useful, best of luck on your mission to get
it fully functional!

The same professor who assigned that project also taught the Assembly
Language class, feel free to check out my project for that as well:
https://github.com/jeffreymcclain/Computer-Organization-and-Assembly-Language-Project.
If I remember correctly, it's a checkers program with a computer opponent,
and you enter your moves using a coordinate system. The graphics /
interface is pretty crude though, be warned ;)

- Jeffrey McClain

**Comment by nerdburt** [comment]
Thanks so much - will check it out!

Rick

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
